name = "c0vc"
version = "0.1.0"
defaultTargets = ["c0vc"]

[[lean_lib]]
name = "C0VC"

[[lean_exe]]
name = "c0vc"
root = "Top"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"
