name = "c0c"
version = "0.1.0"
defaultTargets = ["c0c"]

[[lean_lib]]
name = "C0C"

[[lean_exe]]
name = "c0c"
root = "Top"

[[require]]
name = "Parser"
git = "https://github.com/fgdorais/lean4-parser"
rev = "main"
